[package]
name = "punch"
version = "0.1.0"
authors = ["Mark Price <mark@epickrram.com>"]
homepage = "https://github.com/epickrram/punch"
repository = "https://github.com/epickrram/punch"

[dependencies]
clap = "2.15.0"
chrono = "0.2"

[[bin]]
name = "punch"
path = "src/main.rs"